### ISSUE TITLE
Move to Java 8 and Spring 4.x

### ISSUE THREAD

**Issue by damnhandy** [dschulten/hydra-java#24]
With [Java 6 and 7 no longer being supported by supported by Oracle](http://www.oracle.com/technetwork/java/eol-135779.html) and [Spring 3.x being EOL'd at the end of 2016](https://spring.io/blog/2015/06/15/spring-framework-3-2-x-eol-on-dec-31-2016), i'd like to vote to making Spring 4 and Java 8 the new minimum requirements going forward. There's a lot to be gained by being able to leverage Java 8 language features with JSON-LD.

**Comment by dschulten** [comment]
Done.
