### ISSUE TITLE
Issue with traverson

### ISSUE THREAD

**Issue by mozinrat** [dschulten/hydra-java#30]
While using traveson getting below error 
`java.lang.IllegalStateException: Did not find LinkDiscoverer supporting media type application/vnd.siren+json;charset=UTF-8!`

I am using below configuration
```
@Bean
  public RestOperations restOperations() {
    RestTemplate restTemplate = new RestTemplate();
    restTemplate.setRequestFactory(new HttpComponentsAsyncClientHttpRequestFactory());
    restTemplate.getInterceptors().add(new BasicAuthorizationInterceptor(user, password));
    return restTemplate;
  }

  @Override
  public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
    converters.add(sirenMessageConverter());
  }


  @Bean
  public SirenMessageConverter sirenMessageConverter() {
    SirenMessageConverter sirenMessageConverter = new SirenMessageConverter();
    sirenMessageConverter.setSupportedMediaTypes(Collections.singletonList(SIREN_JSON));
    return sirenMessageConverter;
  }
```

and calling it like
```
Traverson traverson = new Traverson(URI.create(baseUrl+"/api.json"), SIREN_JSON);
traverson.setRestOperations(restOperations);
ResponseEntity<Entity>  entity = traverson.follow("child").toEntity(Entity.class);
```
What am I doing wrong, or this extension doesn't add mediaType support for siren with traverson.
Would be nice if you can build an AutoConfigurationClass

I believe to make it work, we need to add the entry in PluginRegistry with MediaType.SIREN_JSON

**Comment by dschulten** [comment]
Indeed spring-hateoas-ext does not enable Siren for Traverson, it only allows you to render your responses as Siren. Please file an issue with spring-hateoas to add Siren support for Traverson. Looking into the Affordance API currently, as suggested in https://github.com/spring-projects/spring-hateoas/issues/334.
